#!/usr/bin/env python3
"""Vendor the web fonts locally so the app never calls out to a CDN.

`static/index.html` used to pull three stylesheets from `fonts.googleapis.com`.
That's a hard blocker for an offline handheld (the ROG Ally phase) and a privacy
leak besides — every page load told Google someone opened the app. This script
downloads the fonts once and writes a local `static/css/fonts.css`.

Unlike the extracted game art, these fonts are **committable**: every family
here ships under the SIL Open Font License, which permits redistribution. The
generated `static/fonts/OFL.txt` records that.

    python3 tools/vendor_fonts.py           # download + write fonts.css
    python3 tools/vendor_fonts.py --check   # verify local files satisfy the CSS

Only the latin + latin-ext subsets are kept — the app is English-only and the
full set would multiply the payload for glyphs nothing renders.
"""
from __future__ import annotations

import argparse
import os
import re
import sys
import urllib.request

# Matches the families index.html previously requested from the CDN.
FAMILIES = [
    "Cinzel:wght@500;700",
    "Crimson+Text:ital@0;1",
    "Space+Mono",
    "Pixelify+Sans:wght@400;500;700",
    "VT323",
    "Atkinson+Hyperlegible:ital,wght@0,400;0,700;1,400",
]

# woff2 is served only to browsers that advertise support.
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

KEEP_SUBSETS = ("latin", "latin-ext")

HEADER = """/* ════════════════════════════════════════════════════════════════════════
   fonts.css — GENERATED by tools/vendor_fonts.py. Do not hand-edit.

   Self-hosted so the app makes ZERO external requests: required for the
   offline handheld build, and it stops every page load pinging a CDN.
   All families are SIL Open Font License — see static/fonts/OFL.txt.
   ════════════════════════════════════════════════════════════════════════ */
"""


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="verify every file fonts.css references exists")
    args = ap.parse_args()

    repo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    font_dir = os.path.join(repo, "static", "fonts")
    css_path = os.path.join(repo, "static", "css", "fonts.css")

    if args.check:
        if not os.path.isfile(css_path):
            sys.exit(f"missing {css_path} — run without --check first")
        with open(css_path, encoding="utf-8") as fh:
            css = fh.read()
        # the API emits unquoted url(...) — accept either form
        refs = re.findall(r'url\(\s*["\']?(/fonts/[^)"\']+)["\']?\s*\)', css)
        if not refs:
            sys.exit("fonts.css declares no local font files — regeneration failed")
        missing = [r for r in refs
                   if not os.path.isfile(os.path.join(repo, "static", r.lstrip("/")))]
        print(f"{len(refs)} font references, {len(missing)} missing")
        for m in missing:
            print(f"  MISSING {m}")
        if "googleapis" in css or "gstatic" in css:
            sys.exit("fonts.css still references a CDN host")
        print("no CDN references — offline-safe" if not missing else "")
        return 1 if missing else 0

    os.makedirs(font_dir, exist_ok=True)
    url = ("https://fonts.googleapis.com/css2?"
           + "&".join(f"family={f}" for f in FAMILIES) + "&display=swap")
    print(f"fetching stylesheet for {len(FAMILIES)} families …")
    css = fetch(url).decode("utf-8")

    # The API emits: /* subset */ then an @font-face block per subset.
    blocks = re.split(r"(/\*\s*[a-z0-9-]+\s*\*/)", css)
    out: list[str] = [HEADER]
    downloaded = 0
    skipped = 0

    for i in range(1, len(blocks) - 1, 2):
        subset = blocks[i].strip("/* ").strip()
        body = blocks[i + 1]
        if subset not in KEEP_SUBSETS:
            skipped += 1
            continue
        m = re.search(r"src:\s*url\((https://[^)]+\.woff2)\)", body)
        fam = re.search(r"font-family:\s*'([^']+)'", body)
        if not m or not fam:
            continue
        remote = m.group(1)
        weight = re.search(r"font-weight:\s*([^;]+);", body)
        style = re.search(r"font-style:\s*([^;]+);", body)
        slug = (fam.group(1).lower().replace(" ", "-")
                + f"-{(weight.group(1).strip() if weight else '400')}"
                + (f"-{style.group(1).strip()}" if style and
                   style.group(1).strip() != "normal" else "")
                + f"-{subset}.woff2")
        dest = os.path.join(font_dir, slug)
        if not os.path.isfile(dest):
            with open(dest, "wb") as fh:
                fh.write(fetch(remote))
            downloaded += 1
        out.append(body.replace(remote, f"/fonts/{slug}").strip() + "\n")

    with open(css_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))

    licence = os.path.join(font_dir, "OFL.txt")
    if not os.path.isfile(licence):
        with open(licence, "w", encoding="utf-8") as fh:
            fh.write(
                "The fonts in this directory are redistributed under the SIL Open\n"
                "Font License 1.1, which permits bundling and redistribution.\n\n"
                "Families: Cinzel, Crimson Text, Space Mono, Pixelify Sans, VT323,\n"
                "Atkinson Hyperlegible.\n\n"
                "Full licence text: https://scripts.sil.org/OFL\n"
                "Sources: https://fonts.google.com/\n\n"
                "Vendored by tools/vendor_fonts.py so the app makes no external\n"
                "requests at runtime.\n"
            )

    total = sum(os.path.getsize(os.path.join(font_dir, f))
                for f in os.listdir(font_dir) if f.endswith(".woff2"))
    print(f"downloaded {downloaded} files ({skipped} non-latin subsets skipped)")
    print(f"static/fonts/  {total/1024:.0f} KB")
    print(f"wrote {css_path}")
    print("\nnow drop the CDN <link>s from static/index.html and load /css/fonts.css")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
